<?php

/**
 * Implements hook_menu().
 */
function steve_cases_arhive_menu()
{
  $items['cases_arhive'] = array(
    'title' => 'Архів справ',
    'page callback' => 'steve_cases_arhive_page',
    'access arguments' => array('access content'),
    'weight' => 1,
  );

  return $items;
}

/**
 * Menu callback; prints a listing of active nodes on the site.
 */
function steve_cases_arhive_page()
{


  $terms = taxonomy_get_tree(2);
  return theme('item_list', array('items' => _steve_cases_arhive_taxonomy_tree($terms)));
}

/**
 * Helper for mymodule_taxonomy_tree()
 */
function _steve_cases_arhive_taxonomy_tree($terms, $parent = 0)
{
  $items = array();

  foreach ($terms as $term) {
    if (in_array($parent, $term->parents)) {
      $data = new stdClass();
      $data->name = '<span class="termName">' . $term->name . '</span>';
      $data->nodes_count = '';
      $data->description = '';
      $data->nodes = '';

      $nodes = taxonomy_select_nodes(array($term->tid));
      $nodes_count = count($nodes);

      if ($nodes_count > 0) {
        $data->nodes_count = '<span class="nodesCount">(' . $nodes_count . ')</span> ';
        $nodes = node_load_multiple($nodes);

        foreach ($nodes as $nid => $node) {
          $nodes[$nid] = array(
            'data' => '<div class="' . (($node->field_files) ? 'caseWithVideo' : 'caseWithOutVideo') . '"></div>' .
              '<span class="caseTitle">' . l(check_plain($node->title), 'node/' . $node->nid) . '</span>' .
              '<div class="caseDescription">' .
              truncate_utf8(trim(decode_entities(strip_tags($node->body['und'][0]['value']))), 150, TRUE, TRUE) .
              '</div>',
          );


        }
        $data->nodes = theme('item_list', array('items' => $nodes));

      }
      if (!empty($term->description)) {
        $data->description = '<div class="termDescription">' . trim(decode_entities(strip_tags($term->description))) . '</div>';

      }

      $items[] = array(
        'data' => '<div class="folder"></div>' . $data->nodes_count . $data->name . $data->description . $data->nodes,
        'children' => _steve_cases_arhive_taxonomy_tree($terms, $term->tid),
      );
    }
  }

  return $items;
}

